version: '3'
services:

  mongodb:
    image: mongo:6.0.3
    restart: unless-stopped
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_DATABASE: my-test
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-super}
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: unless-stopped
    ports:
      - "9980:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-super}
    depends_on:
      - mongodb

volumes:
  mongodb_data: